version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=englishcenter;User=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;
      - Jwt__Issuer=englishcentermanagement
      - Jwt__Audience=englishcentermanagement
      - Jwt__Key=key@englishcentermanagement123456789
    ports:
      - "12915:80"

  database:
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    volumes:
      - englistcentermanagement-database:/var/opt/mssql
 
  web-admin:
    environment:
      - REACT_APP_ENP=http://api/api/
    ports:
      - "12916:80"
  web-staff:
    environment:
      - REACT_APP_ENP=http://api/api/
    ports:
      - "12917:80"
  web-student:
    environment:
      - REACT_APP_ENP=http://api/api/
    ports:
      - "12918:80"
  web-teacher:
    environment:
      - REACT_APP_ENP=http://api/api/
    ports:
      - "12919:80"

volumes:
  englishcentermanagement-database:
    external: true
