version: '3.8'

services:
  webapi:
    image: engcenmgr-webapi:latest
    build:
      context: .
      dockerfile: Backend/EnglishCenterManagement/Dockerfile
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest

  web-admin:
    image: engcenmgr-webadmin:latest
    build:
      context: Frontend Web/admin-app-react
    depends_on:
      - webapi

  web-staff:
    image: engcenmgr-webstaff:latest
    build:
      context: Frontend Web/staff-app-react
    depends_on:
      - webapi

  web-student:
    image: engcenmgr-webstudent:latest
    build:
      context: Frontend Web/student-app-react
    depends_on:
      - webapi

  web-teacher:
    image: engcenmgr-webteacher:latest
    build:
      context: Frontend Web/teacher-app-react
    depends_on:
      - webapi
