export const UserRoutePaths = {
  GET_ADMINS: "/admins",
  GET_ADMIN: "/admin/:id",
  CREATE_ADMIN: "/admin/create",
  EDIT_ADMIN: "/admin/edit/:id",
  GET_STAFFS: "/staffs",
  GET_STAFF: "/staff/:id",
  CREATE_STAFF: "/staff/create",
  EDIT_STAFF: "/staff/edit/:id",
  GET_TEACHERS: "/teachers",
  GET_TEACHER: "/teacher/:id",
  CREATE_TEACHER: "/teacher/create",
  EDIT_TEACHER: "/teacher/edit/:id",
  GET_STUDENTS: "/students",
  GET_STUDENT: "/student/:id",
  EDIT_STUDENT: "/student/edit/:id",
  CREATE_STUDENT: "/student/create",
};

export const UserPaths = {
  GET_ADMINS: () => "/admins",
  GET_STAFFS: () => "/staffs",
  GET_STAFF: (id: number) => `/staff/${id}`,
  GET_TEACHERS: () => "/teachers",
  GET_TEACHER: (id: number) => `/teacher/${id}`,
  CREATE_TEACHER: () => "/teacher/create",
  EDIT_TEACHER: (id: number) => `/teacher/edit/${id}`,
  GET_STUDENTS: () => "/students",
  GET_STUDENT: (id: number) => `/student/${id}`,
  EDIT_STUDENT: (id: number) => `/student/edit/${id}`,
  CREATE_STUDENT: () => "/student/create",
};
